CREATE TABLE [Machines] (

    [WORKERS] INTEGER NOT NULL,
    [BATCH_SIZE] INTEGER NOT NULL,
    [LATENCY] INTEGER NOT NULL,
    [TIME1] DOUBLE,
    [TIME2] DOUBLE,
    [ACCURACY] DOUBLE


);
  
